/**
* 00PSBannerApp UC2 - Banner Display Application
*
* This class demonstrates the creation of a visual banner displaying the word "00PS"
* using ASCII art composed of asterisks (*) and spaces. The banner is printed to the
* console using individual print statements for each line, creating a decorative
* text effect.
*
* <p>The banner is generated by printing predefined string patterns line by line,
* where each line contributes to forming the letters 0, 0, P, and S in a stylized format.
* This extends a basic user story by adding visual presentation to a simple message output.
* </p>
*
*@author Developer
* @version 2
*/

public class OOPSBannerApp {
    public static void main(String[] args) {
        // Define the segments for each letter row by row
        String[] row0 = {" *** ", " *** ", "**** ", " ****"};
        String[] row1 = {"*   *", "*   *", "*   *", "*    "};
        String[] row2 = {"*   *", "*   *", "**** ", " *** "};
        String[] row3 = {"*   *", "*   *", "*    ", "    *"};
        String[] row4 = {" *** ", " *** ", "*    ", "**** "};

        // Use String.join to build each line with a 2-space delimiter
        String space = "  ";

        System.out.println(String.join(space, row0));
        System.out.println(String.join(space, row1));
        System.out.println(String.join(space, row2));
        System.out.println(String.join(space, row3));
        System.out.println(String.join(space, row4));
    }
}
